package seed

import "github.com/Teamthy/i-confess/internal/models"

// This file is the canonical confession corpus for I CONFESS.
//
// It exists for the same reason categories_canonical.go does: launch content
// has to be a reviewable, testable artefact in the repository, not rows typed
// into a database by hand. It is the single authority for what a fresh
// deployment contains, in every environment - see EnsureContent.
//
// Rules enforced by confessions_canonical_test.go:
//
//  1. Every one of the 39 canonical categories has at least two published
//     confessions. Decision D3 makes this a launch requirement: the marketing
//     site claims "39 areas of life" and the catalogue has to be able to
//     support the claim.
//  2. Every category name referenced here exists in CanonicalCategories.
//  3. Titles are unique. A duplicate title is two rows the user cannot tell
//     apart.
//  4. Short, Medium and Long are all non-empty and strictly increasing in
//     length. The session engine picks a variant by duration; a variant that
//     is shorter than the one below it breaks that choice.
//  5. Every confession carries at least one Scripture reference. A confession
//     with no reference is an affirmation, and this is not an affirmation app.
//
// IsDirectQuote is true only where the confession text quotes the verse
// closely enough that a reader comparing them would recognise the wording.
// Alluding to a verse is not quoting it, and claiming otherwise overstates
// the biblical warrant for the words a user is being asked to speak.

// CanonicalConfession is one authored confession.
type CanonicalConfession struct {
	Category string
	Title    string

	// Three lengths, because the session engine assembles a queue to fit a
	// requested duration and picks the variant that best fills it.
	Short  string
	Medium string
	Long   string

	Scriptures []models.ScriptureRef
	Intensity  int // 1 gentle, 5 urgent
}

// CanonicalConfessions is the launch library.
var CanonicalConfessions = []CanonicalConfession{

	{Category: "Healing", Title: "I Am Healed", Intensity: 3,
		Short:  "By His stripes, I am healed.",
		Medium: "I declare that by the stripes of Jesus I am healed. Sickness has no authority over my body. I receive wholeness now.",
		Long:   "I declare that by the stripes of Jesus I am healed. Sickness and disease have no authority over my body, for my body is the temple of the Holy Spirit. I receive wholeness in every organ, every tissue, and every cell. The life of God flows through me, restoring strength, health, and vitality. I walk in divine health all the days of my life.",
		Scriptures: []models.ScriptureRef{
			{Book: "Isaiah", Chapter: 53, Verse: "5", Translation: "KJV", IsDirectQuote: true},
			{Book: "1 Peter", Chapter: 2, Verse: "24", Translation: "KJV", IsDirectQuote: true},
			{Book: "Psalm", Chapter: 103, Verse: "2-3", Translation: "KJV", IsDirectQuote: false},
		}},
	{Category: "Healing", Title: "Divine Health", Intensity: 2,
		Short:  "I walk in divine health.",
		Medium: "I walk in divine health and wholeness. Every day my strength is renewed like the eagle's.",
		Long:   "I walk in divine health and wholeness. Every day my strength is renewed like the eagle's. The same Spirit that raised Christ from the dead lives in me and quickens my mortal body. I am strong, I am whole, and I refuse to accept any report that contradicts the finished work of the cross.",
		Scriptures: []models.ScriptureRef{
			{Book: "Romans", Chapter: 8, Verse: "11", Translation: "KJV", IsDirectQuote: true},
			{Book: "Isaiah", Chapter: 40, Verse: "31", Translation: "KJV", IsDirectQuote: false},
		}},
	{Category: "Faith", Title: "Faith That Moves", Intensity: 3,
		Short:  "My faith moves mountains.",
		Medium: "I have the faith of God. I speak to my mountains and they move. Nothing is impossible for me.",
		Long:   "I have the God-kind of faith. I speak to the mountains in my life and they move. I believe without wavering, for I know that the word of God cannot fail. My faith grows stronger every day as I hear and confess the word. Nothing shall be impossible for me because I believe.",
		Scriptures: []models.ScriptureRef{
			{Book: "Mark", Chapter: 11, Verse: "22-24", Translation: "KJV", IsDirectQuote: true},
			{Book: "Romans", Chapter: 10, Verse: "17", Translation: "KJV", IsDirectQuote: false},
		}},
	{Category: "Faith", Title: "Unshakable Trust", Intensity: 2,
		Short:  "I trust in the Lord with all my heart.",
		Medium: "I trust in the Lord with all my heart and lean not on my own understanding. He directs my paths.",
		Long:   "I trust in the Lord with all my heart and lean not on my own understanding. In all my ways I acknowledge Him, and He directs my paths. I will not be shaken, for my confidence is in the Lord and not in man. My steps are ordered by God.",
		Scriptures: []models.ScriptureRef{
			{Book: "Proverbs", Chapter: 3, Verse: "5-6", Translation: "KJV", IsDirectQuote: true},
		}},
	{Category: "Finance", Title: "I Am Prosperous", Intensity: 3,
		Short:  "I am abundantly provided for.",
		Medium: "I declare that I am blessed in the city and blessed in the field. My God supplies all my needs according to His riches.",
		Long:   "I declare that I am blessed in the city and blessed in the field, blessed coming in and blessed going out. My God supplies all my needs according to His riches in glory. I am a generous giver, and the windows of heaven are open over my life. Wealth and riches are in my house because I honor the Lord.",
		Scriptures: []models.ScriptureRef{
			{Book: "Deuteronomy", Chapter: 28, Verse: "3-6", Translation: "KJV", IsDirectQuote: true},
			{Book: "Philippians", Chapter: 4, Verse: "19", Translation: "KJV", IsDirectQuote: true},
		}},
	{Category: "Finance", Title: "Steward of Abundance", Intensity: 2,
		Short:  "I am a wise steward.",
		Medium: "I am a faithful steward of all God entrusts to me. Wisdom guides my financial decisions.",
		Long:   "I am a faithful and wise steward of everything God entrusts to my hands. Wisdom guides my financial decisions, and I am diligent in my labor. I honor God with the firstfruits of my increase, and my barns are filled with plenty. Poverty is far from me.",
		Scriptures: []models.ScriptureRef{
			{Book: "Proverbs", Chapter: 3, Verse: "9-10", Translation: "KJV", IsDirectQuote: false},
			{Book: "Luke", Chapter: 16, Verse: "10", Translation: "KJV", IsDirectQuote: false},
		}},
	{Category: "Marriage", Title: "A Blessed Union", Intensity: 2,
		Short:  "My marriage is blessed.",
		Medium: "My marriage is founded on Christ. I love and honor my spouse, and our home is filled with peace.",
		Long:   "My marriage is founded on the rock of Christ. I love and honor my spouse with patience and kindness. Our home is filled with peace, joy, and the presence of God. What God has joined together, no one can separate. We are heirs together of the grace of life.",
		Scriptures: []models.ScriptureRef{
			{Book: "Ephesians", Chapter: 5, Verse: "25", Translation: "KJV", IsDirectQuote: false},
			{Book: "Mark", Chapter: 10, Verse: "9", Translation: "KJV", IsDirectQuote: true},
		}},
	{Category: "Purpose", Title: "Called With Purpose", Intensity: 3,
		Short:  "I was created for a purpose.",
		Medium: "I was created for a divine purpose. My steps are ordered, and I fulfill the good works prepared for me.",
		Long:   "I was created for a divine purpose. Before I was formed in the womb, God knew me and set me apart. My steps are ordered by the Lord, and I fulfill the good works prepared for me before the foundation of the world. I will not live a small life; I will fulfill my assignment with boldness and grace.",
		Scriptures: []models.ScriptureRef{
			{Book: "Jeremiah", Chapter: 1, Verse: "5", Translation: "KJV", IsDirectQuote: true},
			{Book: "Ephesians", Chapter: 2, Verse: "10", Translation: "KJV", IsDirectQuote: true},
		}},
	{Category: "Peace", Title: "Peace Beyond Understanding", Intensity: 1,
		Short:  "The peace of God guards my heart.",
		Medium: "I am not anxious about anything. The peace of God that passes understanding guards my heart and mind.",
		Long:   "I refuse to be anxious about anything. In every situation I bring my requests to God with thanksgiving, and the peace of God that passes all understanding guards my heart and mind in Christ Jesus. I am calm, I am still, and I know that God is with me.",
		Scriptures: []models.ScriptureRef{
			{Book: "Philippians", Chapter: 4, Verse: "6-7", Translation: "KJV", IsDirectQuote: true},
		}},
	{Category: "Wisdom", Title: "Wisdom And Clarity", Intensity: 2,
		Short:  "I walk in wisdom and clarity.",
		Medium: "I walk in wisdom and clarity. If I lack wisdom, I ask of God, and He gives generously.",
		Long:   "I walk in wisdom and clarity. If I lack wisdom, I ask of God, who gives generously to all without finding fault, and it is given to me. The wisdom of God is in me, and I make excellent decisions. I have insight, understanding, and discernment for every situation.",
		Scriptures: []models.ScriptureRef{
			{Book: "James", Chapter: 1, Verse: "5", Translation: "KJV", IsDirectQuote: true},
			{Book: "Proverbs", Chapter: 3, Verse: "5-6", Translation: "KJV", IsDirectQuote: false},
		}},
	{Category: "Protection", Title: "Under His Wings", Intensity: 2,
		Short:  "I am safe under His wings.",
		Medium: "I dwell in the secret place of the Most High and abide under the shadow of the Almighty. No evil befalls me.",
		Long:   "I dwell in the secret place of the Most High and abide under the shadow of the Almighty. He is my refuge and my fortress, my God in whom I trust. No evil shall befall me, nor any plague come near my dwelling, for He gives His angels charge over me.",
		Scriptures: []models.ScriptureRef{
			{Book: "Psalm", Chapter: 91, Verse: "1-2", Translation: "KJV", IsDirectQuote: true},
		}},
	{Category: "Emotional Strength", Title: "Renewed Strength", Intensity: 3,
		Short:  "My strength is renewed.",
		Medium: "I am strong in the Lord and in the power of His might. I can do all things through Christ who strengthens me.",
		Long:   "I am strong in the Lord and in the power of His might. I can do all things through Christ who strengthens me. Those who wait on the Lord renew their strength; I mount up with wings as eagles, I run and do not grow weary, I walk and do not faint.",
		Scriptures: []models.ScriptureRef{
			{Book: "Philippians", Chapter: 4, Verse: "13", Translation: "KJV", IsDirectQuote: true},
			{Book: "Isaiah", Chapter: 40, Verse: "31", Translation: "KJV", IsDirectQuote: true},
		}},
	{Category: "Business", Title: "Fruitful Work", Intensity: 2,
		Short:  "The work of my hands is blessed.",
		Medium: "The Lord blesses the work of my hands. I am diligent, and my labor is fruitful.",
		Long:   "The Lord blesses all the work of my hands. I am diligent in my business and faithful in the small things, therefore I am entrusted with more. My enterprise flourishes, my ideas are excellent, and I bring value to everyone I serve. I operate with wisdom and integrity.",
		Scriptures: []models.ScriptureRef{
			{Book: "Deuteronomy", Chapter: 28, Verse: "12", Translation: "KJV", IsDirectQuote: false},
			{Book: "Proverbs", Chapter: 22, Verse: "29", Translation: "KJV", IsDirectQuote: false},
		}},
	{Category: "Joy", Title: "Joy Unspeakable", Intensity: 1,
		Short:  "The joy of the Lord is my strength.",
		Medium: "The joy of the Lord is my strength. I am filled with joy unspeakable and full of glory.",
		Long:   "The joy of the Lord is my strength. I am filled with joy unspeakable and full of glory. This is the day the Lord has made, and I will rejoice and be glad in it. My heart is glad, and my countenance is bright, for the Lord has done great things for me.",
		Scriptures: []models.ScriptureRef{
			{Book: "Nehemiah", Chapter: 8, Verse: "10", Translation: "KJV", IsDirectQuote: true},
		}},
	{Category: "Identity", Title: "I Am Who God Says", Intensity: 3,
		Short:  "I am a child of God.",
		Medium: "I am a child of God, fearfully and wonderfully made. I am accepted in the Beloved.",
		Long:   "I am a child of God, fearfully and wonderfully made. I am accepted in the Beloved, chosen before the foundation of the world. I am the head and not the tail, above and not beneath. My identity is not defined by my past, my mistakes, or the opinions of others, but by the word of God.",
		Scriptures: []models.ScriptureRef{
			{Book: "1 John", Chapter: 3, Verse: "1", Translation: "KJV", IsDirectQuote: false},
			{Book: "Psalm", Chapter: 139, Verse: "14", Translation: "KJV", IsDirectQuote: true},
		}},
	{Category: "Gratitude", Title: "A Grateful Heart", Intensity: 1,
		Short:  "I enter His gates with thanksgiving.",
		Medium: "I enter His gates with thanksgiving and His courts with praise. My heart is full of gratitude.",
		Long:   "I enter His gates with thanksgiving and His courts with praise. I am grateful for the goodness of God in my life. In everything I give thanks, for this is the will of God in Christ Jesus concerning me. My heart overflows with gratitude, and I bless the Lord at all times.",
		Scriptures: []models.ScriptureRef{
			{Book: "Psalm", Chapter: 100, Verse: "4", Translation: "KJV", IsDirectQuote: true},
			{Book: "1 Thessalonians", Chapter: 5, Verse: "18", Translation: "KJV", IsDirectQuote: true},
		}},

	// ── Categories that carried a single confession ─────────────────────

	{Category: "Marriage", Title: "What God Has Joined", Intensity: 2,
		Short:  "My marriage is held together by God.",
		Medium: "I declare that what God has joined together, no one can separate. Christ is the third strand in my marriage, and a threefold cord is not quickly broken.",
		Long:   "I declare that what God has joined together, no one can separate. Christ is the third strand in my marriage, and a threefold cord is not quickly broken. I choose covenant over convenience, and commitment over feeling. Where I have been harsh, I soften. Where I have been silent, I speak kindness. Our disagreements are handled with honour, not contempt, and we do not let the sun go down on our anger. Our home is a place where both of us are safe.",
		Scriptures: []models.ScriptureRef{
			{Book: "Mark", Chapter: 10, Verse: "9", Translation: "KJV", IsDirectQuote: true},
			{Book: "Ecclesiastes", Chapter: 4, Verse: "12", Translation: "KJV", IsDirectQuote: true},
			{Book: "Ephesians", Chapter: 4, Verse: "26", Translation: "KJV", IsDirectQuote: false},
		}},
	{Category: "Purpose", Title: "His Workmanship", Intensity: 2,
		Short:  "I am created for good works prepared for me.",
		Medium: "I declare that I am God's workmanship, created in Christ Jesus for good works which He prepared beforehand. My life is not an accident; it is an assignment.",
		Long:   "I declare that I am God's workmanship, created in Christ Jesus for good works which He prepared beforehand. My life is not an accident; it is an assignment. Before I was formed, He knew me and set me apart. I am not competing for someone else's calling, and I do not measure my worth by their progress. The work in front of me today is the work He prepared, and I have everything I need to do it faithfully.",
		Scriptures: []models.ScriptureRef{
			{Book: "Ephesians", Chapter: 2, Verse: "10", Translation: "KJV", IsDirectQuote: true},
			{Book: "Jeremiah", Chapter: 1, Verse: "5", Translation: "KJV", IsDirectQuote: false},
		}},
	{Category: "Peace", Title: "Perfect Peace", Intensity: 2,
		Short:  "My mind is kept in perfect peace.",
		Medium: "I declare that the mind stayed on God is kept in perfect peace. My peace is not the absence of trouble; it is the presence of God inside the trouble.",
		Long:   "I declare that the mind stayed on God is kept in perfect peace. My peace is not the absence of trouble; it is the presence of God inside the trouble. The peace Jesus left with me is not the peace the world gives, and it cannot be taken by the world either. I refuse to rehearse catastrophe. I bring every anxious thought to Him with thanksgiving, and the peace that passes understanding stands guard over my heart and mind.",
		Scriptures: []models.ScriptureRef{
			{Book: "Isaiah", Chapter: 26, Verse: "3", Translation: "KJV", IsDirectQuote: true},
			{Book: "John", Chapter: 14, Verse: "27", Translation: "KJV", IsDirectQuote: true},
			{Book: "Philippians", Chapter: 4, Verse: "6-7", Translation: "KJV", IsDirectQuote: false},
		}},
	{Category: "Wisdom", Title: "Ask And Receive", Intensity: 2,
		Short:  "God gives wisdom generously to all who ask.",
		Medium: "I declare that if any of me lacks wisdom, I may ask God, who gives generously without finding fault. I do not have to guess my way through life.",
		Long:   "I declare that if any of me lacks wisdom, I may ask God, who gives generously without finding fault. I do not have to guess my way through life. Christ has become wisdom for me, so I am never cut off from the mind of God. I ask in faith, I listen before I act, and I value counsel over my own first instinct. Where I have been impulsive, I slow down; where I have been timid, I decide.",
		Scriptures: []models.ScriptureRef{
			{Book: "James", Chapter: 1, Verse: "5", Translation: "KJV", IsDirectQuote: true},
			{Book: "1 Corinthians", Chapter: 1, Verse: "30", Translation: "KJV", IsDirectQuote: false},
			{Book: "Proverbs", Chapter: 2, Verse: "6", Translation: "KJV", IsDirectQuote: false},
		}},
	{Category: "Protection", Title: "His Angels Have Charge", Intensity: 3,
		Short:  "The Lord gives His angels charge over me.",
		Medium: "I declare that the Lord gives His angels charge over me, to keep me in all my ways. The name of the Lord is a strong tower, and I run into it and am safe.",
		Long:   "I declare that the Lord gives His angels charge over me, to keep me in all my ways. The name of the Lord is a strong tower, and I run into it and am safe. The Lord is faithful and establishes me, keeping me from evil. I go out and come in under His covering, and my household travels under the same guard. No weapon formed against us prospers, and no harm reaches our dwelling.",
		Scriptures: []models.ScriptureRef{
			{Book: "Psalm", Chapter: 91, Verse: "11", Translation: "KJV", IsDirectQuote: true},
			{Book: "Proverbs", Chapter: 18, Verse: "10", Translation: "KJV", IsDirectQuote: true},
			{Book: "2 Thessalonians", Chapter: 3, Verse: "3", Translation: "KJV", IsDirectQuote: false},
		}},
	{Category: "Emotional Strength", Title: "He Is Near The Brokenhearted", Intensity: 2,
		Short:  "The Lord is near to the brokenhearted.",
		Medium: "I declare that the Lord is near to the brokenhearted and saves those of a contrite spirit. My grief is not hidden from Him, and I do not have to be well before I come to Him.",
		Long:   "I declare that the Lord is near to the brokenhearted and saves those of a contrite spirit. My grief is not hidden from Him, and I do not have to be well before I come to Him. He gives power to the faint and increases strength where there is none. I do not despise my own slow healing. What I feel today is allowed, and it is not the last word about me. Joy comes in the morning, and until it does, His presence is enough.",
		Scriptures: []models.ScriptureRef{
			{Book: "Psalm", Chapter: 34, Verse: "18", Translation: "KJV", IsDirectQuote: true},
			{Book: "Isaiah", Chapter: 40, Verse: "29", Translation: "KJV", IsDirectQuote: false},
			{Book: "Psalm", Chapter: 30, Verse: "5", Translation: "KJV", IsDirectQuote: false},
		}},
	{Category: "Business", Title: "A Good Name Over Riches", Intensity: 2,
		Short:  "A good name is better than great riches.",
		Medium: "I declare that a good name is chosen rather than great riches, and that the Lord gives me power to get wealth. I will not trade integrity for margin.",
		Long:   "I declare that a good name is chosen rather than great riches, and that the Lord gives me power to get wealth. I will not trade integrity for margin. A false balance is an abomination, but a just weight is His delight, so my dealings are honest whether or not anyone is watching. I commit my work to the Lord and my plans are established. I build slowly, keep my word, pay what I owe, and treat every customer as a person rather than a transaction.",
		Scriptures: []models.ScriptureRef{
			{Book: "Proverbs", Chapter: 22, Verse: "1", Translation: "KJV", IsDirectQuote: true},
			{Book: "Deuteronomy", Chapter: 8, Verse: "18", Translation: "KJV", IsDirectQuote: true},
			{Book: "Proverbs", Chapter: 11, Verse: "1", Translation: "KJV", IsDirectQuote: true},
		}},
	{Category: "Joy", Title: "The Joy Of The Lord", Intensity: 2,
		Short:  "The joy of the Lord is my strength.",
		Medium: "I declare that the joy of the Lord is my strength. My gladness does not depend on my circumstances, because it is rooted in who God is and not in what I have.",
		Long:   "I declare that the joy of the Lord is my strength. My gladness does not depend on my circumstances, because it is rooted in who God is and not in what I have. In His presence is fullness of joy, and at His right hand are pleasures for evermore. Though the fig tree does not blossom, yet I will rejoice in the Lord. I choose gratitude today, and I refuse to let a bad hour dictate the tone of my whole life.",
		Scriptures: []models.ScriptureRef{
			{Book: "Nehemiah", Chapter: 8, Verse: "10", Translation: "KJV", IsDirectQuote: true},
			{Book: "Psalm", Chapter: 16, Verse: "11", Translation: "KJV", IsDirectQuote: true},
			{Book: "Habakkuk", Chapter: 3, Verse: "17-18", Translation: "KJV", IsDirectQuote: false},
		}},
	{Category: "Identity", Title: "A New Creation", Intensity: 3,
		Short:  "I am a new creation in Christ.",
		Medium: "I declare that if any man is in Christ, he is a new creation: old things have passed away and all things have become new. My past is not my identity.",
		Long:   "I declare that if any man is in Christ, he is a new creation: old things have passed away and all things have become new. My past is not my identity. I am crucified with Christ, and the life I now live I live by faith in the Son of God. I am chosen, adopted, and called out of darkness into His marvellous light. What I used to be is true, but it is not current, and I decline every label that contradicts what God has already said about me.",
		Scriptures: []models.ScriptureRef{
			{Book: "2 Corinthians", Chapter: 5, Verse: "17", Translation: "KJV", IsDirectQuote: true},
			{Book: "Galatians", Chapter: 2, Verse: "20", Translation: "KJV", IsDirectQuote: true},
			{Book: "1 Peter", Chapter: 2, Verse: "9", Translation: "KJV", IsDirectQuote: false},
		}},
	{Category: "Gratitude", Title: "In Everything Give Thanks", Intensity: 1,
		Short:  "I give thanks in everything.",
		Medium: "I declare that in everything I give thanks, for this is the will of God concerning me. Gratitude is not denial of what is hard; it is trust in who is good.",
		Long:   "I declare that in everything I give thanks, for this is the will of God concerning me. Gratitude is not denial of what is hard; it is trust in who is good. I enter His gates with thanksgiving and His courts with praise. The peace of God rules in my heart, and to that peace I was called in one body, and I am thankful. I notice what has been given rather than only what is missing, and I let thankfulness shape the words I speak over my own life.",
		Scriptures: []models.ScriptureRef{
			{Book: "1 Thessalonians", Chapter: 5, Verse: "18", Translation: "KJV", IsDirectQuote: true},
			{Book: "Psalm", Chapter: 100, Verse: "4", Translation: "KJV", IsDirectQuote: true},
			{Book: "Colossians", Chapter: 3, Verse: "15", Translation: "KJV", IsDirectQuote: false},
		}},

	// ── Categories that carried no confession at all ────────────────────

	{Category: "Health", Title: "The Temple Of The Spirit", Intensity: 2,
		Short:  "My body is the temple of the Holy Spirit.",
		Medium: "I declare that my body is the temple of the Holy Spirit and I am not my own. I honour God with my body, because it was bought at a price.",
		Long:   "I declare that my body is the temple of the Holy Spirit and I am not my own. I honour God with my body, because it was bought at a price. A merry heart does good like medicine, so I guard what I allow to live in my mind. I treat sleep, food, and rest as stewardship rather than indulgence. I am not at war with my body; I am caring for something entrusted to me, and I ask for the strength to keep doing it.",
		Scriptures: []models.ScriptureRef{
			{Book: "1 Corinthians", Chapter: 6, Verse: "19-20", Translation: "KJV", IsDirectQuote: true},
			{Book: "Proverbs", Chapter: 17, Verse: "22", Translation: "KJV", IsDirectQuote: true},
		}},
	{Category: "Health", Title: "Prospering And In Health", Intensity: 2,
		Short:  "I pray that I may prosper and be in health.",
		Medium: "I declare that God would have me prosper and be in health, even as my soul prospers. Wholeness of body and soul belong together, and I claim both.",
		Long:   "I declare that God would have me prosper and be in health, even as my soul prospers. Wholeness of body and soul belong together, and I claim both. The Lord heals my diseases and redeems my life from destruction. I do not romanticise suffering, and I do not treat my body as disposable. Where I need healing, I ask. Where I need help, I accept it. Where I need rest, I take it without shame.",
		Scriptures: []models.ScriptureRef{
			{Book: "3 John", Chapter: 1, Verse: "2", Translation: "KJV", IsDirectQuote: true},
			{Book: "Psalm", Chapter: 103, Verse: "3", Translation: "KJV", IsDirectQuote: false},
		}},
	{Category: "Wealth", Title: "The Blessing Makes Rich", Intensity: 2,
		Short:  "The blessing of the Lord makes rich.",
		Medium: "I declare that the blessing of the Lord makes rich, and He adds no sorrow with it. What He gives me, I can hold without it holding me.",
		Long:   "I declare that the blessing of the Lord makes rich, and He adds no sorrow with it. What He gives me, I can hold without it holding me. God gives me power to get wealth, and He is able to make all grace abound toward me so that I always have enough for every good work. I am not afraid of increase, and I am not seduced by it. Wealth is a tool in my hands, not a master over my heart.",
		Scriptures: []models.ScriptureRef{
			{Book: "Proverbs", Chapter: 10, Verse: "22", Translation: "KJV", IsDirectQuote: true},
			{Book: "2 Corinthians", Chapter: 9, Verse: "8", Translation: "KJV", IsDirectQuote: false},
		}},
	{Category: "Wealth", Title: "Charge Them That Are Rich", Intensity: 3,
		Short:  "I do not set my heart on uncertain riches.",
		Medium: "I declare that I will not be highminded nor trust in uncertain riches, but in the living God, who gives me richly all things to enjoy.",
		Long:   "I declare that I will not be highminded nor trust in uncertain riches, but in the living God, who gives me richly all things to enjoy. I am rich in good works, ready to distribute and willing to share, laying up a foundation that cannot be shaken. Money moves through my hands; it does not sit on my heart. I give generously, keep records honestly, and remember that everything I steward was given to me first.",
		Scriptures: []models.ScriptureRef{
			{Book: "1 Timothy", Chapter: 6, Verse: "17-19", Translation: "KJV", IsDirectQuote: true},
			{Book: "Matthew", Chapter: 6, Verse: "21", Translation: "KJV", IsDirectQuote: false},
		}},
	{Category: "Breakthrough", Title: "The Breaker Goes Up", Intensity: 3,
		Short:  "The Breaker goes up before me.",
		Medium: "I declare that the Breaker has gone up before me. The wall I have been staring at is not the end of my story; it is the place the breakthrough starts.",
		Long:   "I declare that the Breaker has gone up before me. The wall I have been staring at is not the end of my story; it is the place the breakthrough starts. The weapons of my warfare are mighty through God to the pulling down of strongholds. God is doing a new thing; it springs forth and I perceive it. I stop negotiating with what He has already decided to break, and I walk through the opening He makes.",
		Scriptures: []models.ScriptureRef{
			{Book: "Micah", Chapter: 2, Verse: "13", Translation: "KJV", IsDirectQuote: true},
			{Book: "2 Corinthians", Chapter: 10, Verse: "4", Translation: "KJV", IsDirectQuote: true},
			{Book: "Isaiah", Chapter: 43, Verse: "19", Translation: "KJV", IsDirectQuote: false},
		}},
	{Category: "Breakthrough", Title: "Enlarging My Territory", Intensity: 3,
		Short:  "God enlarges my territory.",
		Medium: "I declare that God enlarges my territory and His hand is with me. What looked like a ceiling is being removed, and I will not shrink back from the room He is making.",
		Long:   "I declare that God enlarges my territory and His hand is with me. What looked like a ceiling is being removed, and I will not shrink back from the room He is making. I ask boldly, believing that He is able to do exceedingly abundantly above all that I ask or think. Where delay has taught me patience, patience is now producing endurance. I step forward into the next size of my life without apology.",
		Scriptures: []models.ScriptureRef{
			{Book: "1 Chronicles", Chapter: 4, Verse: "10", Translation: "KJV", IsDirectQuote: true},
			{Book: "Ephesians", Chapter: 3, Verse: "20", Translation: "KJV", IsDirectQuote: false},
			{Book: "James", Chapter: 1, Verse: "3-4", Translation: "KJV", IsDirectQuote: false},
		}},
	{Category: "Relationships", Title: "Iron Sharpens Iron", Intensity: 2,
		Short:  "God surrounds me with people who sharpen me.",
		Medium: "I declare that as iron sharpens iron, so one person sharpens another. I choose the company that makes me better, and I am that person for someone else.",
		Long:   "I declare that as iron sharpens iron, so one person sharpens another. I choose the company that makes me better, and I am that person for someone else. Two are better than one, for if they fall, one will lift up his fellow. I live peaceably with all people as far as it depends on me. I release relationships that only take, I invest in the ones that build, and I am honest enough to be sharpened rather than defended.",
		Scriptures: []models.ScriptureRef{
			{Book: "Proverbs", Chapter: 27, Verse: "17", Translation: "KJV", IsDirectQuote: true},
			{Book: "Ecclesiastes", Chapter: 4, Verse: "9-10", Translation: "KJV", IsDirectQuote: true},
			{Book: "Romans", Chapter: 12, Verse: "18", Translation: "KJV", IsDirectQuote: false},
		}},
	{Category: "Relationships", Title: "Restored And Reconciled", Intensity: 2,
		Short:  "God restores what was broken between us.",
		Medium: "I declare that God is a reconciler. Where a relationship has fractured, I choose the harder obedience of repair over the easier comfort of resentment.",
		Long:   "I declare that God is a reconciler. Where a relationship has fractured, I choose the harder obedience of repair over the easier comfort of resentment. I forgive as I have been forgiven, and I speak truth in love rather than silence that hardens. Not every relationship can be restored, and I trust God with the ones that cannot. But where restoration is possible, I will not be the one who refuses it.",
		Scriptures: []models.ScriptureRef{
			{Book: "2 Corinthians", Chapter: 5, Verse: "18", Translation: "KJV", IsDirectQuote: false},
			{Book: "Ephesians", Chapter: 4, Verse: "32", Translation: "KJV", IsDirectQuote: false},
		}},
	{Category: "Family", Title: "As For Me And My House", Intensity: 3,
		Short:  "As for me and my house, we serve the Lord.",
		Medium: "I declare that as for me and my house, we will serve the Lord. My home has a direction, and I am responsible for the part of it that is mine.",
		Long:   "I declare that as for me and my house, we will serve the Lord. My home has a direction, and I am responsible for the part of it that is mine. Except the Lord builds the house, they labour in vain that build it, so I build on Him rather than on my own effort. My household is covered, provided for, and taught. What my family could not fix in the last generation stops with me.",
		Scriptures: []models.ScriptureRef{
			{Book: "Joshua", Chapter: 24, Verse: "15", Translation: "KJV", IsDirectQuote: true},
			{Book: "Psalm", Chapter: 127, Verse: "1", Translation: "KJV", IsDirectQuote: true},
		}},
	{Category: "Family", Title: "My Household Is Held", Intensity: 2,
		Short:  "My household is kept by the Lord.",
		Medium: "I declare that the Lord keeps my household. My children are taught of the Lord, and great is their peace.",
		Long:   "I declare that the Lord keeps my household. My children are taught of the Lord, and great is their peace. I release the need to control people I cannot control, and I pray over them instead of worrying at them. Our home is a place of mercy, not performance. Where there has been dysfunction, healing begins here. Where there has been absence, presence begins with me.",
		Scriptures: []models.ScriptureRef{
			{Book: "Isaiah", Chapter: 54, Verse: "13", Translation: "KJV", IsDirectQuote: true},
			{Book: "Psalm", Chapter: 121, Verse: "7-8", Translation: "KJV", IsDirectQuote: false},
		}},
	{Category: "Career", Title: "Work As Unto The Lord", Intensity: 2,
		Short:  "I work heartily, as for the Lord.",
		Medium: "I declare that whatever I do, I do it heartily as unto the Lord and not unto men. My work is worship even when no one is applauding it.",
		Long:   "I declare that whatever I do, I do it heartily as unto the Lord and not unto men. My work is worship even when no one is applauding it. Seest thou a man diligent in his business? He shall stand before kings. I am reliable, I finish what I start, and I treat the unglamorous parts of my job with the same care as the visible ones. Favour and promotion come from God, and He is not overlooking my faithfulness.",
		Scriptures: []models.ScriptureRef{
			{Book: "Colossians", Chapter: 3, Verse: "23", Translation: "KJV", IsDirectQuote: true},
			{Book: "Proverbs", Chapter: 22, Verse: "29", Translation: "KJV", IsDirectQuote: true},
		}},
	{Category: "Career", Title: "The Head And Not The Tail", Intensity: 3,
		Short:  "The Lord makes me the head and not the tail.",
		Medium: "I declare that the Lord makes me the head and not the tail, above only and not beneath. My career moves forward under His ordering.",
		Long:   "I declare that the Lord makes me the head and not the tail, above only and not beneath. My career moves forward under His ordering. Doors that were shut are opening, and I will not be so attached to comfort that I miss them. I commit my plans to the Lord and they are established. Where I have been overlooked, my work speaks. Where I have been passed over, God is repositioning me rather than punishing me.",
		Scriptures: []models.ScriptureRef{
			{Book: "Deuteronomy", Chapter: 28, Verse: "13", Translation: "KJV", IsDirectQuote: true},
			{Book: "Proverbs", Chapter: 16, Verse: "3", Translation: "KJV", IsDirectQuote: true},
		}},
	{Category: "Leadership", Title: "Be Strong And Of Good Courage", Intensity: 3,
		Short:  "I am strong and of good courage.",
		Medium: "I declare that the Lord commands me to be strong and of good courage. I do not have to be unafraid to lead; I have to be obedient while I am afraid.",
		Long:   "I declare that the Lord commands me to be strong and of good courage. I do not have to be unafraid to lead; I have to be obedient while I am afraid. Where there is no counsel, the people fall, so I surround myself with wise advisers and I actually listen to them. The work is not mine to carry alone, and the outcome is not mine to guarantee. I lead from conviction, not from the need to be liked.",
		Scriptures: []models.ScriptureRef{
			{Book: "Joshua", Chapter: 1, Verse: "9", Translation: "KJV", IsDirectQuote: true},
			{Book: "Proverbs", Chapter: 11, Verse: "14", Translation: "KJV", IsDirectQuote: true},
		}},
	{Category: "Leadership", Title: "Let No Man Despise My Youth", Intensity: 2,
		Short:  "I am an example in word and conduct.",
		Medium: "I declare that I will be an example in word, in conduct, in love, in spirit, in faith, and in purity. My authority grows out of my character, not my title.",
		Long:   "I declare that I will be an example in word, in conduct, in love, in spirit, in faith, and in purity. My authority grows out of my character, not my title. I set the wall in order the way Nehemiah did: by working alongside the people rather than above them. I take responsibility when things go wrong and give credit when they go right. The people I lead are not a resource to be spent; they are a trust to be developed.",
		Scriptures: []models.ScriptureRef{
			{Book: "1 Timothy", Chapter: 4, Verse: "12", Translation: "KJV", IsDirectQuote: true},
			{Book: "Nehemiah", Chapter: 2, Verse: "18", Translation: "KJV", IsDirectQuote: false},
		}},
	{Category: "Favor", Title: "Favour As A Shield", Intensity: 2,
		Short:  "God surrounds me with favour as with a shield.",
		Medium: "I declare that the Lord blesses the righteous and surrounds me with favour as with a shield. I find grace in the sight of God and people.",
		Long:   "I declare that the Lord blesses the righteous and surrounds me with favour as with a shield. I find grace in the sight of God and people. Jesus increased in wisdom, in stature, and in favour with God and man, and I am being formed the same way. I do not manipulate outcomes; I walk in integrity and let favour do what favour does. Rooms I could not enter by effort open to me by grace.",
		Scriptures: []models.ScriptureRef{
			{Book: "Psalm", Chapter: 5, Verse: "12", Translation: "KJV", IsDirectQuote: true},
			{Book: "Luke", Chapter: 2, Verse: "52", Translation: "KJV", IsDirectQuote: true},
			{Book: "Proverbs", Chapter: 3, Verse: "4", Translation: "KJV", IsDirectQuote: false},
		}},
	{Category: "Favor", Title: "Grace That Finds Me", Intensity: 1,
		Short:  "Grace goes before me.",
		Medium: "I declare that God's favour rests on my work and establishes it. What I receive is not always what I earned, and I am willing to receive it.",
		Long:   "I declare that God's favour rests on my work and establishes it. What I receive is not always what I earned, and I am willing to receive it. I let go of the belief that I must qualify for every good thing. Grace reaches people who have not finished becoming ready, and it has reached me. I receive help, receive opportunity, and receive kindness without insisting that I deserve it first.",
		Scriptures: []models.ScriptureRef{
			{Book: "Psalm", Chapter: 90, Verse: "17", Translation: "KJV", IsDirectQuote: true},
			{Book: "Ephesians", Chapter: 2, Verse: "8", Translation: "KJV", IsDirectQuote: false},
		}},

	{Category: "Provision", Title: "All My Need Supplied", Intensity: 2,
		Short:  "God supplies all my need.",
		Medium: "I declare that my God supplies all my need according to His riches in glory by Christ Jesus. I am not depending on my salary; I am depending on His supply.",
		Long:   "I declare that my God supplies all my need according to His riches in glory by Christ Jesus. I am not depending on my salary; I am depending on His supply. The Lord is my shepherd and I shall not want. I seek first the kingdom of God and His righteousness, and these things are added to me. I give thanks for what has already come, I manage what is in my hands well, and I refuse to make decisions out of scarcity panic.",
		Scriptures: []models.ScriptureRef{
			{Book: "Philippians", Chapter: 4, Verse: "19", Translation: "KJV", IsDirectQuote: true},
			{Book: "Psalm", Chapter: 23, Verse: "1", Translation: "KJV", IsDirectQuote: true},
			{Book: "Matthew", Chapter: 6, Verse: "33", Translation: "KJV", IsDirectQuote: false},
		}},
	{Category: "Provision", Title: "Daily Bread", Intensity: 1,
		Short:  "I receive my daily bread.",
		Medium: "I declare that God gives me this day my daily bread. I do not have to solve next year's provision today; I have to be faithful with today's.",
		Long:   "I declare that God gives me this day my daily bread. I do not have to solve next year's provision today; I have to be faithful with today's. He who gathered much had nothing over, and he who gathered little had no lack. I stop measuring my life by what is stored and start trusting the One who supplies. I ask, I receive, and I share what I have been given.",
		Scriptures: []models.ScriptureRef{
			{Book: "Matthew", Chapter: 6, Verse: "11", Translation: "KJV", IsDirectQuote: true},
			{Book: "Exodus", Chapter: 16, Verse: "18", Translation: "KJV", IsDirectQuote: true},
		}},
	{Category: "Confidence", Title: "I Can Do All Things", Intensity: 3,
		Short:  "I can do all things through Christ.",
		Medium: "I declare that I can do all things through Christ who strengthens me. My confidence is not in my ability; it is in His strength working through my ability.",
		Long:   "I declare that I can do all things through Christ who strengthens me. My confidence is not in my ability; it is in His strength working through my ability. God has not given me a spirit of fear, but of power, love, and a sound mind. If God is for me, who can be against me? I do not need to be certain of the outcome to begin; I need to be certain of who sent me. I begin, and I keep going.",
		Scriptures: []models.ScriptureRef{
			{Book: "Philippians", Chapter: 4, Verse: "13", Translation: "KJV", IsDirectQuote: true},
			{Book: "2 Timothy", Chapter: 1, Verse: "7", Translation: "KJV", IsDirectQuote: true},
			{Book: "Romans", Chapter: 8, Verse: "31", Translation: "KJV", IsDirectQuote: true},
		}},
	{Category: "Confidence", Title: "No Longer A Slave To Opinion", Intensity: 2,
		Short:  "I am not ruled by what people think of me.",
		Medium: "I declare that I am not a servant of men. The approval I chase is the approval I already have, and I stop paying for it with my obedience.",
		Long:   "I declare that I am not a servant of men. The approval I chase is the approval I already have, and I stop paying for it with my obedience. I have been bought with a price, so the opinions of people I barely know do not set my value. Where I have shrunk to stay comfortable for others, I stop. I speak, I ask, I attempt, and I let God be the judge of my worth rather than a crowd.",
		Scriptures: []models.ScriptureRef{
			{Book: "1 Corinthians", Chapter: 7, Verse: "23", Translation: "KJV", IsDirectQuote: true},
			{Book: "Galatians", Chapter: 1, Verse: "10", Translation: "KJV", IsDirectQuote: false},
		}},
	{Category: "Discipline", Title: "I Keep My Body Under", Intensity: 3,
		Short:  "I keep my body under and bring it into subjection.",
		Medium: "I declare that I keep my body under and bring it into subjection. I am not disqualified by appetites I refused to train.",
		Long:   "I declare that I keep my body under and bring it into subjection. I am not disqualified by appetites I refused to train. The grace of God teaches me to deny ungodliness and worldly lusts and to live soberly, righteously, and godly. Self-control is fruit of the Spirit, so this is not willpower alone; it is His power in my habits. I do the small thing consistently, and consistency becomes character.",
		Scriptures: []models.ScriptureRef{
			{Book: "1 Corinthians", Chapter: 9, Verse: "27", Translation: "KJV", IsDirectQuote: true},
			{Book: "Titus", Chapter: 2, Verse: "11-12", Translation: "KJV", IsDirectQuote: true},
			{Book: "Galatians", Chapter: 5, Verse: "22-23", Translation: "KJV", IsDirectQuote: false},
		}},
	{Category: "Discipline", Title: "He That Has No Rule Over His Spirit", Intensity: 3,
		Short:  "I rule my spirit.",
		Medium: "I declare that I am not like a city broken down and without walls. I have rule over my own spirit, and my impulses do not decide my day.",
		Long:   "I declare that I am not like a city broken down and without walls. I have rule over my own spirit, and my impulses do not decide my day. I am slow to anger, quick to listen, and careful with the words I speak when I am provoked. Boundaries are not harshness; they are the walls that make the city safe. I choose the difficult right repeatedly until it is no longer difficult.",
		Scriptures: []models.ScriptureRef{
			{Book: "Proverbs", Chapter: 25, Verse: "28", Translation: "KJV", IsDirectQuote: true},
			{Book: "James", Chapter: 1, Verse: "19", Translation: "KJV", IsDirectQuote: false},
		}},
	{Category: "Hope", Title: "The God Of Hope Fills Me", Intensity: 2,
		Short:  "The God of hope fills me with all joy and peace.",
		Medium: "I declare that the God of hope fills me with all joy and peace in believing, so that I abound in hope through the power of the Holy Spirit.",
		Long:   "I declare that the God of hope fills me with all joy and peace in believing, so that I abound in hope through the power of the Holy Spirit. This hope is an anchor for my soul, both sure and steadfast. It does not make me ashamed, because the love of God is poured into my heart. I have waited before and He came, and I will not conclude that this wait is different because it is longer.",
		Scriptures: []models.ScriptureRef{
			{Book: "Romans", Chapter: 15, Verse: "13", Translation: "KJV", IsDirectQuote: true},
			{Book: "Hebrews", Chapter: 6, Verse: "19", Translation: "KJV", IsDirectQuote: true},
			{Book: "Romans", Chapter: 5, Verse: "5", Translation: "KJV", IsDirectQuote: false},
		}},
	{Category: "Hope", Title: "New Every Morning", Intensity: 1,
		Short:  "His mercies are new every morning.",
		Medium: "I declare that it is of the Lord's mercies that I am not consumed, because His compassions fail not. They are new every morning; great is His faithfulness.",
		Long:   "I declare that it is of the Lord's mercies that I am not consumed, because His compassions fail not. They are new every morning; great is His faithfulness. For I know the thoughts He thinks toward me: thoughts of peace and not of evil, to give me an expected end. Yesterday's failure did not exhaust His mercy, and today is not a repeat of yesterday. I begin again, and beginning again is not weakness.",
		Scriptures: []models.ScriptureRef{
			{Book: "Lamentations", Chapter: 3, Verse: "22-23", Translation: "KJV", IsDirectQuote: true},
			{Book: "Jeremiah", Chapter: 29, Verse: "11", Translation: "KJV", IsDirectQuote: true},
		}},
	{Category: "Freedom", Title: "Whom The Son Sets Free", Intensity: 3,
		Short:  "Whom the Son sets free is free indeed.",
		Medium: "I declare that whom the Son sets free is free indeed. I stand fast in the liberty Christ has given me, and I will not be entangled again with a yoke of bondage.",
		Long:   "I declare that whom the Son sets free is free indeed. I stand fast in the liberty Christ has given me, and I will not be entangled again with a yoke of bondage. Where the Spirit of the Lord is, there is liberty. The chains I could not break by trying harder have already been broken, and my work now is to walk out of the cell rather than break it. I am not returning to what I have been delivered from.",
		Scriptures: []models.ScriptureRef{
			{Book: "John", Chapter: 8, Verse: "36", Translation: "KJV", IsDirectQuote: true},
			{Book: "Galatians", Chapter: 5, Verse: "1", Translation: "KJV", IsDirectQuote: true},
			{Book: "2 Corinthians", Chapter: 3, Verse: "17", Translation: "KJV", IsDirectQuote: true},
		}},
	{Category: "Freedom", Title: "The Captives Are Released", Intensity: 3,
		Short:  "I am released from every captivity.",
		Medium: "I declare that the Spirit of the Lord is upon me to proclaim liberty to the captives and the opening of the prison to those who are bound. I am among the released.",
		Long:   "I declare that the Spirit of the Lord is upon me to proclaim liberty to the captives and the opening of the prison to those who are bound. I am among the released. Addictions, compulsions, shame, and old patterns do not own me any longer. I speak this over the specific thing I have been unable to name: it is losing its grip. I receive deliverance, I keep the door closed, and I walk in the daylight rather than negotiating in the dark.",
		Scriptures: []models.ScriptureRef{
			{Book: "Isaiah", Chapter: 61, Verse: "1", Translation: "KJV", IsDirectQuote: true},
			{Book: "Luke", Chapter: 4, Verse: "18", Translation: "KJV", IsDirectQuote: true},
		}},
	{Category: "Spiritual Growth", Title: "Grow In Grace", Intensity: 2,
		Short:  "I grow in grace and in knowledge.",
		Medium: "I declare that I grow in grace and in the knowledge of our Lord and Saviour Jesus Christ. Maturity is a direction, not an arrival, and I am moving.",
		Long:   "I declare that I grow in grace and in the knowledge of our Lord and Saviour Jesus Christ. Maturity is a direction, not an arrival, and I am moving. He who began a good work in me will perform it until the day of Jesus Christ. I am rooted and built up in Him, established in the faith. Speaking the truth in love, I grow up into Him in all things. I am not the same believer I was a year ago, and I am not finished.",
		Scriptures: []models.ScriptureRef{
			{Book: "2 Peter", Chapter: 3, Verse: "18", Translation: "KJV", IsDirectQuote: true},
			{Book: "Philippians", Chapter: 1, Verse: "6", Translation: "KJV", IsDirectQuote: true},
			{Book: "Colossians", Chapter: 2, Verse: "6-7", Translation: "KJV", IsDirectQuote: false},
		}},
	{Category: "Spiritual Growth", Title: "As Ye Have Received Christ", Intensity: 2,
		Short:  "I walk in Him as I received Him.",
		Medium: "I declare that as I have received Christ Jesus the Lord, so I walk in Him. What began my faith also sustains it; I do not graduate past the gospel.",
		Long:   "I declare that as I have received Christ Jesus the Lord, so I walk in Him. What began my faith also sustains it; I do not graduate past the gospel. I feed on the word, not only on feeling. I pray when I do not feel like it and trust the discipline over the mood. I ask for a heart that is teachable, because the fastest way to stop growing is to assume I have already arrived.",
		Scriptures: []models.ScriptureRef{
			{Book: "Colossians", Chapter: 2, Verse: "6", Translation: "KJV", IsDirectQuote: true},
			{Book: "1 Peter", Chapter: 2, Verse: "2", Translation: "KJV", IsDirectQuote: false},
		}},
	{Category: "Prayer", Title: "Be Careful For Nothing", Intensity: 2,
		Short:  "I pray about everything and worry about nothing.",
		Medium: "I declare that I will be careful for nothing, but in everything by prayer and supplication with thanksgiving I make my requests known to God.",
		Long:   "I declare that I will be careful for nothing, but in everything by prayer and supplication with thanksgiving I make my requests known to God. I ask and it is given, I seek and I find, I knock and it is opened. The effectual fervent prayer of a righteous person avails much. I do not treat prayer as a last resort after I have exhausted my options; it is the first thing I do, and it changes both the situation and me.",
		Scriptures: []models.ScriptureRef{
			{Book: "Philippians", Chapter: 4, Verse: "6", Translation: "KJV", IsDirectQuote: true},
			{Book: "James", Chapter: 5, Verse: "16", Translation: "KJV", IsDirectQuote: true},
			{Book: "Matthew", Chapter: 7, Verse: "7", Translation: "KJV", IsDirectQuote: false},
		}},
	{Category: "Prayer", Title: "Pray Without Ceasing", Intensity: 1,
		Short:  "I pray without ceasing.",
		Medium: "I declare that I pray without ceasing. Prayer is not an event on my calendar; it is the atmosphere I live in.",
		Long:   "I declare that I pray without ceasing. Prayer is not an event on my calendar; it is the atmosphere I live in. I bring the ordinary moments to God as well as the emergencies. I pray in the Spirit on all occasions, staying alert and keeping at it. My conversations with Him are honest rather than performed, and I would rather be understood by God than impressive to anyone else.",
		Scriptures: []models.ScriptureRef{
			{Book: "1 Thessalonians", Chapter: 5, Verse: "17", Translation: "KJV", IsDirectQuote: true},
			{Book: "Ephesians", Chapter: 6, Verse: "18", Translation: "KJV", IsDirectQuote: false},
		}},
	{Category: "Children", Title: "My Children Are The Lord's", Intensity: 2,
		Short:  "My children are a heritage of the Lord.",
		Medium: "I declare that my children are a heritage of the Lord and the fruit of the womb is His reward. They were given to me, not owned by me.",
		Long:   "I declare that my children are a heritage of the Lord and the fruit of the womb is His reward. They were given to me, not owned by me. Out of the mouths of babes and sucklings He has ordained strength. I train them in the way they should go, and I trust the training to outlast my anxiety. They are His before they are mine, and He is a better Father to them than I could ever be.",
		Scriptures: []models.ScriptureRef{
			{Book: "Psalm", Chapter: 127, Verse: "3", Translation: "KJV", IsDirectQuote: true},
			{Book: "Proverbs", Chapter: 22, Verse: "6", Translation: "KJV", IsDirectQuote: true},
			{Book: "Psalm", Chapter: 8, Verse: "2", Translation: "KJV", IsDirectQuote: false},
		}},
	{Category: "Children", Title: "Taught Of The Lord", Intensity: 2,
		Short:  "My children are taught of the Lord.",
		Medium: "I declare that all my children are taught of the Lord, and great is the peace of my children. No weapon formed against them prospers.",
		Long:   "I declare that all my children are taught of the Lord, and great is the peace of my children. No weapon formed against them prospers. They will make mistakes, and mistakes are not the end of them. I speak life over their futures rather than fear over their failures. What runs in my family line does not have to run in theirs, and I stand in the gap for them in prayer.",
		Scriptures: []models.ScriptureRef{
			{Book: "Isaiah", Chapter: 54, Verse: "13", Translation: "KJV", IsDirectQuote: true},
			{Book: "Isaiah", Chapter: 54, Verse: "17", Translation: "KJV", IsDirectQuote: true},
		}},
	{Category: "Parenting", Title: "Not Provoking To Anger", Intensity: 2,
		Short:  "I raise my children without provoking them.",
		Medium: "I declare that I do not provoke my children to wrath, but bring them up in the nurture and admonition of the Lord.",
		Long:   "I declare that I do not provoke my children to wrath, but bring them up in the nurture and admonition of the Lord. I discipline with patience and correct without cruelty. These words I keep in my own heart first, and I teach them diligently in the ordinary moments: sitting at home, walking by the way, lying down and rising up. I apologise when I am wrong, because that teaches them more than perfection ever could.",
		Scriptures: []models.ScriptureRef{
			{Book: "Ephesians", Chapter: 6, Verse: "4", Translation: "KJV", IsDirectQuote: true},
			{Book: "Deuteronomy", Chapter: 6, Verse: "6-7", Translation: "KJV", IsDirectQuote: true},
		}},
	{Category: "Parenting", Title: "Train And Trust", Intensity: 2,
		Short:  "I train my child and trust the Lord with the result.",
		Medium: "I declare that correction gives wisdom, and that I will not withhold discipline from those I love. I train, and then I release the outcome to God.",
		Long:   "I declare that correction gives wisdom, and that I will not withhold discipline from those I love. I train, and then I release the outcome to God. I am not the saviour of my children; I am their parent, and that is a smaller and more faithful job. I stop trying to control what I cannot and start praying over what I can. Where I have failed them, mercy is available to both of us.",
		Scriptures: []models.ScriptureRef{
			{Book: "Proverbs", Chapter: 29, Verse: "15", Translation: "KJV", IsDirectQuote: true},
			{Book: "Proverbs", Chapter: 29, Verse: "17", Translation: "KJV", IsDirectQuote: true},
		}},
	{Category: "Direction", Title: "He Directs My Paths", Intensity: 2,
		Short:  "I trust the Lord and He directs my paths.",
		Medium: "I declare that I trust in the Lord with all my heart and lean not on my own understanding. In all my ways I acknowledge Him, and He directs my paths.",
		Long:   "I declare that I trust in the Lord with all my heart and lean not on my own understanding. In all my ways I acknowledge Him, and He directs my paths. He instructs me and teaches me in the way I should go, guiding me with His eye. When I turn to the right or to the left, I hear a voice behind me saying, this is the way, walk in it. I do not need to see the whole road to take the next step correctly.",
		Scriptures: []models.ScriptureRef{
			{Book: "Proverbs", Chapter: 3, Verse: "5-6", Translation: "KJV", IsDirectQuote: true},
			{Book: "Psalm", Chapter: 32, Verse: "8", Translation: "KJV", IsDirectQuote: true},
			{Book: "Isaiah", Chapter: 30, Verse: "21", Translation: "KJV", IsDirectQuote: true},
		}},
	{Category: "Direction", Title: "At The Crossroads", Intensity: 2,
		Short:  "God gives wisdom for this decision.",
		Medium: "I declare that if I lack wisdom for this decision, I ask God, who gives generously. I do not have to choose in the dark.",
		Long:   "I declare that if I lack wisdom for this decision, I ask God, who gives generously. I do not have to choose in the dark. I am not paralysed by the fear of choosing wrongly; God is able to redirect a sincere decision. I gather counsel, I weigh the cost, I pray honestly about what I actually want, and then I move. Indecision is also a decision, and I decline to make it.",
		Scriptures: []models.ScriptureRef{
			{Book: "James", Chapter: 1, Verse: "5", Translation: "KJV", IsDirectQuote: true},
			{Book: "Proverbs", Chapter: 15, Verse: "22", Translation: "KJV", IsDirectQuote: true},
			{Book: "Luke", Chapter: 14, Verse: "28", Translation: "KJV", IsDirectQuote: false},
		}},
	{Category: "Creativity", Title: "Filled With The Spirit Of Wisdom", Intensity: 2,
		Short:  "God fills me with skill and creativity.",
		Medium: "I declare that God fills me with the spirit of wisdom, understanding, and knowledge in all manner of workmanship to devise cunning works.",
		Long:   "I declare that God fills me with the spirit of wisdom, understanding, and knowledge in all manner of workmanship to devise cunning works. I am made in the image of a Maker, so making is not a hobby I picked up; it is how I was designed. I am His workmanship, created for good works. I make things that are true and useful and beautiful, and I do not wait for permission to begin.",
		Scriptures: []models.ScriptureRef{
			{Book: "Exodus", Chapter: 31, Verse: "3-5", Translation: "KJV", IsDirectQuote: true},
			{Book: "Genesis", Chapter: 1, Verse: "27", Translation: "KJV", IsDirectQuote: false},
		}},
	{Category: "Creativity", Title: "Fearfully And Wonderfully Made", Intensity: 2,
		Short:  "I am fearfully and wonderfully made.",
		Medium: "I declare that I am fearfully and wonderfully made, and my work is not a copy of someone else's. What I make carries the fingerprint of how I was made.",
		Long:   "I declare that I am fearfully and wonderfully made, and my work is not a copy of someone else's. What I make carries the fingerprint of how I was made. I stop comparing my first draft to someone else's finished piece. I finish things, I show them to people, and I accept criticism without treating it as verdict. The gift I have is mine to steward, and burying it is not humility.",
		Scriptures: []models.ScriptureRef{
			{Book: "Psalm", Chapter: 139, Verse: "14", Translation: "KJV", IsDirectQuote: true},
			{Book: "Matthew", Chapter: 25, Verse: "25", Translation: "KJV", IsDirectQuote: false},
		}},
	{Category: "Productivity", Title: "Redeeming The Time", Intensity: 2,
		Short:  "I redeem the time.",
		Medium: "I declare that I walk circumspectly, not as a fool but as wise, redeeming the time because the days are evil. My attention is a resource and I spend it deliberately.",
		Long:   "I declare that I walk circumspectly, not as a fool but as wise, redeeming the time because the days are evil. My attention is a resource and I spend it deliberately. The thoughts of the diligent tend only to plenteousness, but everyone who is hasty comes to poverty. I do the important thing before the urgent thing. I finish what I start, I stop starting what I will not finish, and I let rest be productive too.",
		Scriptures: []models.ScriptureRef{
			{Book: "Ephesians", Chapter: 5, Verse: "15-16", Translation: "KJV", IsDirectQuote: true},
			{Book: "Proverbs", Chapter: 21, Verse: "5", Translation: "KJV", IsDirectQuote: true},
		}},
	{Category: "Productivity", Title: "So Built We The Wall", Intensity: 2,
		Short:  "I set my mind to the work and finish it.",
		Medium: "I declare that I set my mind to the work the way Nehemiah did, and I do not come down from it to answer every distraction that calls my name.",
		Long:   "I declare that I set my mind to the work the way Nehemiah did, and I do not come down from it to answer every distraction that calls my name. So built we the wall, and all the wall was joined together. I protect deep work, I say no without guilt, and I measure the day by what moved forward rather than by how busy I felt. Small daily progress compounds, and I trust compounding over intensity.",
		Scriptures: []models.ScriptureRef{
			{Book: "Nehemiah", Chapter: 6, Verse: "3", Translation: "KJV", IsDirectQuote: true},
			{Book: "Nehemiah", Chapter: 6, Verse: "15-16", Translation: "KJV", IsDirectQuote: false},
		}},
	{Category: "Rest", Title: "I Will Give You Rest", Intensity: 1,
		Short:  "Jesus gives my soul rest.",
		Medium: "I declare that I come to Jesus, who is meek and lowly in heart, and I find rest for my soul. His yoke is easy and His burden is light.",
		Long:   "I declare that I come to Jesus, who is meek and lowly in heart, and I find rest for my soul. His yoke is easy and His burden is light. There remains a rest for the people of God, and I enter it rather than earning my way out of it. Rest is not the reward for finished work; it is the foundation for work that lasts. I lie down and sleep in peace, because the Lord alone makes me dwell in safety.",
		Scriptures: []models.ScriptureRef{
			{Book: "Matthew", Chapter: 11, Verse: "28-30", Translation: "KJV", IsDirectQuote: true},
			{Book: "Hebrews", Chapter: 4, Verse: "9-10", Translation: "KJV", IsDirectQuote: false},
			{Book: "Psalm", Chapter: 4, Verse: "8", Translation: "KJV", IsDirectQuote: false},
		}},
	{Category: "Rest", Title: "My Presence Shall Go With Thee", Intensity: 1,
		Short:  "God gives me rest on every side.",
		Medium: "I declare that His presence goes with me and He gives me rest. I stop working from a place of striving and start working from a place of rest.",
		Long:   "I declare that His presence goes with me and He gives me rest. I stop working from a place of striving and start working from a place of rest. The Lord gives power to the faint, and to those who have no might He increases strength. Even the youths shall faint and be weary, but those who wait on the Lord shall renew their strength. Waiting on Him is not wasted time; it is how the strength comes back.",
		Scriptures: []models.ScriptureRef{
			{Book: "Exodus", Chapter: 33, Verse: "14", Translation: "KJV", IsDirectQuote: true},
			{Book: "Isaiah", Chapter: 40, Verse: "29-31", Translation: "KJV", IsDirectQuote: false},
		}},
	{Category: "Forgiveness", Title: "If We Confess", Intensity: 2,
		Short:  "When I confess, He is faithful to forgive.",
		Medium: "I declare that if I confess my sins, God is faithful and just to forgive me and to cleanse me from all unrighteousness. I do not have to carry what He has already taken.",
		Long:   "I declare that if I confess my sins, God is faithful and just to forgive me and to cleanse me from all unrighteousness. I do not have to carry what He has already taken. He removes my transgressions from me as far as the east is from the west. I stop re-prosecuting myself for what has been acquitted. Where I have wronged someone, I make it right where I can, and where I cannot, I release it to God and refuse to keep paying for it in shame.",
		Scriptures: []models.ScriptureRef{
			{Book: "1 John", Chapter: 1, Verse: "9", Translation: "KJV", IsDirectQuote: true},
			{Book: "Psalm", Chapter: 103, Verse: "12", Translation: "KJV", IsDirectQuote: true},
		}},
	{Category: "Forgiveness", Title: "Forgiving One Another", Intensity: 3,
		Short:  "I forgive as Christ forgave me.",
		Medium: "I declare that I am kind and tenderhearted, forgiving one another even as God for Christ's sake has forgiven me. I release the debt I have been carrying.",
		Long:   "I declare that I am kind and tenderhearted, forgiving one another even as God for Christ's sake has forgiven me. I release the debt I have been carrying. Forbearing one another and forgiving one another, if any of us has a quarrel against another. Forgiveness is not saying the harm did not happen; it is refusing to let it keep deciding my life. I hand the case to the only Judge who is qualified to hold it, and I stop rehearsing it.",
		Scriptures: []models.ScriptureRef{
			{Book: "Ephesians", Chapter: 4, Verse: "32", Translation: "KJV", IsDirectQuote: true},
			{Book: "Colossians", Chapter: 3, Verse: "13", Translation: "KJV", IsDirectQuote: true},
		}},
	{Category: "Love", Title: "Love Suffers Long", Intensity: 2,
		Short:  "I love patiently and kindly.",
		Medium: "I declare that love suffers long and is kind. It does not envy, it does not behave itself unseverely, it is not easily provoked, and it thinks no evil.",
		Long:   "I declare that love suffers long and is kind. It does not envy, it does not behave itself unseverely, it is not easily provoked, and it thinks no evil. It bears all things, believes all things, hopes all things, endures all things. Love never fails, and everything I build without it will not outlast me. I am being taught to love in the small daily ways rather than only in the large dramatic ones.",
		Scriptures: []models.ScriptureRef{
			{Book: "1 Corinthians", Chapter: 13, Verse: "4-8", Translation: "KJV", IsDirectQuote: true},
		}},
	{Category: "Love", Title: "We Love Because He First Loved", Intensity: 2,
		Short:  "I love because He first loved me.",
		Medium: "I declare that I love because He first loved me. My capacity to love is not generated by me; it is poured into my heart by the Holy Spirit.",
		Long:   "I declare that I love because He first loved me. My capacity to love is not generated by me; it is poured into my heart by the Holy Spirit. A new commandment He gives me, that I love one another as He has loved me. I love people who are difficult to love, including the version of myself I find hardest. Where my love has run thin, I ask Him to fill it rather than trying harder on my own.",
		Scriptures: []models.ScriptureRef{
			{Book: "1 John", Chapter: 4, Verse: "19", Translation: "KJV", IsDirectQuote: true},
			{Book: "Romans", Chapter: 5, Verse: "5", Translation: "KJV", IsDirectQuote: false},
			{Book: "John", Chapter: 13, Verse: "34", Translation: "KJV", IsDirectQuote: false},
		}},
	{Category: "Overcoming Fear", Title: "No Spirit Of Fear", Intensity: 3,
		Short:  "God has not given me a spirit of fear.",
		Medium: "I declare that God has not given me a spirit of fear, but of power, and of love, and of a sound mind. Fear is not from Him, so it does not get the final word.",
		Long:   "I declare that God has not given me a spirit of fear, but of power, and of love, and of a sound mind. Fear is not from Him, so it does not get the final word. When I am afraid, I will trust in Him. Fear not, for I am with thee; be not dismayed, for I am thy God. I will strengthen thee, yea, I will help thee. I name the fear out loud rather than letting it run unnamed, and I bring it into the light where it loses its size.",
		Scriptures: []models.ScriptureRef{
			{Book: "2 Timothy", Chapter: 1, Verse: "7", Translation: "KJV", IsDirectQuote: true},
			{Book: "Isaiah", Chapter: 41, Verse: "10", Translation: "KJV", IsDirectQuote: true},
			{Book: "Psalm", Chapter: 56, Verse: "3", Translation: "KJV", IsDirectQuote: true},
		}},
	{Category: "Overcoming Fear", Title: "I Sought The Lord And He Delivered Me", Intensity: 2,
		Short:  "He delivered me from all my fears.",
		Medium: "I declare that I sought the Lord and He heard me, and delivered me from all my fears. My anxiety is not a character flaw; it is a thing He has already addressed.",
		Long:   "I declare that I sought the Lord and He heard me, and delivered me from all my fears. My anxiety is not a character flaw; it is a thing He has already addressed. I cast all my care upon Him, because He cares for me. He is near to me when I cannot sleep, and I do not have to perform composure to be loved. I breathe, I pray, I take the next small action, and I do not demand certainty before I move.",
		Scriptures: []models.ScriptureRef{
			{Book: "Psalm", Chapter: 34, Verse: "4", Translation: "KJV", IsDirectQuote: true},
			{Book: "1 Peter", Chapter: 5, Verse: "7", Translation: "KJV", IsDirectQuote: true},
		}},
	{Category: "Success", Title: "This Book Shall Not Depart", Intensity: 3,
		Short:  "I meditate on the word and prosper.",
		Medium: "I declare that the book of the law does not depart out of my mouth. I meditate on it day and night, and then I make my way prosperous and have good success.",
		Long:   "I declare that the book of the law does not depart out of my mouth. I meditate on it day and night, and then I make my way prosperous and have good success. I commit my works to the Lord and my thoughts are established. I pursue achievement without compromising what I believe: no shortcut that costs my integrity, no gain that costs my family. Success I can keep is success built on something that does not move.",
		Scriptures: []models.ScriptureRef{
			{Book: "Joshua", Chapter: 1, Verse: "8", Translation: "KJV", IsDirectQuote: true},
			{Book: "Proverbs", Chapter: 16, Verse: "3", Translation: "KJV", IsDirectQuote: true},
		}},
	{Category: "Success", Title: "Like A Tree Planted", Intensity: 2,
		Short:  "I am like a tree planted by the rivers of water.",
		Medium: "I declare that I am like a tree planted by the rivers of water, bringing forth fruit in its season. Whatever I do prospers, and my leaf does not wither.",
		Long:   "I declare that I am like a tree planted by the rivers of water, bringing forth fruit in its season. Whatever I do prospers, and my leaf does not wither. I do not envy the speed of others, because fruit comes in season and seasons differ. I am planted, not scattered, and my roots go down before my results show up. What I am building is meant to last, and I am building it accordingly.",
		Scriptures: []models.ScriptureRef{
			{Book: "Psalm", Chapter: 1, Verse: "1-3", Translation: "KJV", IsDirectQuote: true},
		}},
	{Category: "Destiny", Title: "An Expected End", Intensity: 3,
		Short:  "God has plans to give me an expected end.",
		Medium: "I declare that God knows the thoughts He thinks toward me: thoughts of peace and not of evil, to give me an expected end. My future is not an accident.",
		Long:   "I declare that God knows the thoughts He thinks toward me: thoughts of peace and not of evil, to give me an expected end. My future is not an accident. He who began a good work in me will complete it. The Lord will perfect that which concerns me, and His mercy endures for ever. All things work together for good to those who love God, and even the parts I did not choose are being used.",
		Scriptures: []models.ScriptureRef{
			{Book: "Jeremiah", Chapter: 29, Verse: "11", Translation: "KJV", IsDirectQuote: true},
			{Book: "Psalm", Chapter: 138, Verse: "8", Translation: "KJV", IsDirectQuote: true},
			{Book: "Romans", Chapter: 8, Verse: "28", Translation: "KJV", IsDirectQuote: true},
		}},
	{Category: "Destiny", Title: "Walking Into What Was Prepared", Intensity: 3,
		Short:  "I walk into what God prepared for me.",
		Medium: "I declare that I walk into the good works God prepared beforehand for me. I am not late, I am not missed, and I am not walking into someone else's calling.",
		Long:   "I declare that I walk into the good works God prepared beforehand for me. I am not late, I am not missed, and I am not walking into someone else's calling. He has called me by name and I am His. The delays I have experienced did not cancel the destination, and the closed doors did not mean the journey ended. I step forward with confidence, because the One who planned my future is the One who goes ahead of me into it.",
		Scriptures: []models.ScriptureRef{
			{Book: "Ephesians", Chapter: 2, Verse: "10", Translation: "KJV", IsDirectQuote: true},
			{Book: "Isaiah", Chapter: 43, Verse: "1", Translation: "KJV", IsDirectQuote: false},
		}},
}
