-- 0015_retention_versioning.sql — PHASE 38 / G-21 / G-22.
--
-- Every durable application row carries a nullable deletion tombstone and a
-- monotonic row version. Existing domain `version` columns are preserved: some
-- are content versions and consent-policy versions, not optimistic-lock values.
-- `row_version` is the uniform concurrency/versioning contract. The retention
-- package increments it whenever it writes a tombstone or restores a row.
--
-- Keep these statements explicit. db.InitSchema also consumes SchemaSQL as a
-- semicolon-delimited bootstrap script, and explicit ALTER statements work for
-- both the migration runner and that compatibility path.

ALTER TABLE admin_users ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE admin_users ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE audio_assets ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE audio_assets ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE audio_checksums ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE audio_checksums ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE audio_downloads ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE audio_downloads ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE audio_events ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE audio_events ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE audio_generation_jobs ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE audio_generation_jobs ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE audio_playback_sessions ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE audio_playback_sessions ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE audio_processing_logs ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE audio_processing_logs ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE audio_qoe_metrics ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE audio_qoe_metrics ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE audio_variants ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE audio_variants ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE collection_categories ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE collection_categories ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE collections ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE collections ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE community_posts ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE community_posts ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE community_reactions ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE community_reactions ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE confession_categories ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE confession_categories ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE confession_variants ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE confession_variants ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE confession_voices ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE confession_voices ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE confessions ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE confessions ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE consent_records ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE consent_records ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE content_moderation_history ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE content_moderation_history ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE content_versions ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE content_versions ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE deletion_records ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE deletion_records ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE email_verification_tokens ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE email_verification_tokens ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE favorites ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE favorites ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE feature_flags ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE feature_flags ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE idempotency_keys ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE idempotency_keys ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE mfa_secrets ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE mfa_secrets ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE moderation_cases ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE moderation_cases ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE notification_preferences ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE notification_preferences ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE outbox_events ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE outbox_events ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE password_reset_tokens ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE password_reset_tokens ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE playback_history ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE playback_history ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE playback_progress ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE playback_progress ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE refresh_tokens ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE refresh_tokens ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE reports ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE reports ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE scheduled_deliveries ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE scheduled_deliveries ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE schedules ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE schedules ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE scripture_references ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE scripture_references ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE security_events ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE security_events ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE session_items ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE session_items ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE session_preferences ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE session_preferences ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE session_progress ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE session_progress ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE signed_urls ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE signed_urls ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE store_notifications ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE store_notifications ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE subscription_plans ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE subscription_plans ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE trials ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE trials ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE user_collection_items ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE user_collection_items ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE user_collections ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE user_collections ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE user_confession_audio ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE user_confession_audio ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE user_confessions ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE user_confessions ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE user_devices ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE user_devices ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE user_identities ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE user_identities ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE user_interests ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE user_interests ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE user_preferences ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE user_preferences ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE user_templates ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE user_templates ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE user_voice_preferences ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE user_voice_preferences ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE users ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE voice_licenses ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE voice_licenses ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE voice_rights ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE voice_rights ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE voices ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE voices ADD COLUMN IF NOT EXISTS row_version INTEGER NOT NULL DEFAULT 1;
